### ISSUE TITLE
Validate nway matching with container segmented by Suite2P

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/ophys_nway_matching#44]
I was reminded that the current nway_matching strategy provides to the module both valid and invalid ROIs and that the nway module itself does not make any distinction between these inputs.

A little bit of recollection from @matchings :
```
from what i recall, Fuhui wanted to provide all the available ROIs to the matching to give it the best chance of finding a match
there are definitely cases where a clear match is found, but the cell is deemed valid in one experiment and invalid in another
but thats a good point that with suite2P the output including invalid stuff is way messier and might cause problems here
```
The concern about suite2P is that it generates many more small and invalid ROIs than the old segmentation pipeline, so we want to make sure that nway matching still performs well with those inputs.

Tasks:
- [x] Choose a container that has been old-segmented, matched, and which scientists have looked at and said "yes, these were good results"
- [x] Pass the full container's worth of experiments through the Suite2P segmentation pipeline.
- [ ] Option 1: Wait for new classifier to be ready. Perform new classification and then run nway matching on the container run.
- [x] Option 2: match to production ROIs to generate a proxy for the new classification and run matching on those proxy labels.
- [x] Compare match counts (nway and pariwise results) from old way vs. new. Confirm they are close.
- [x] Inspect results, in consultation with Marina, Kate, et. al. to get a feel for if something is really wrong, or the strategy needs to be adjusted.

Validatiion:
- [ ] Possibility 1: Agreement that no action is needed.
- [ ] Possibility 2: Agreement that a change is needed, and a new story is written to move that forward.
- [x] Possibility 3: Not enough information to make a conclusion

**Comment by matchings** [comment]
Here is a container that "looks good" to start with: container_id: 829561794 

![container_829561794](https://user-images.githubusercontent.com/21346970/96945780-7a53ea80-1493-11eb-9fad-b53fd939ab41.png)

![container_829561794](https://user-images.githubusercontent.com/21346970/96945789-85a71600-1493-11eb-97ec-ecd986fdfa8e.png)

**Comment by wbwakeman** [comment]
@wbwakeman  @matchings Could you please provide a brief summary of what happens when an invalid ROI gets matched to a valid ROI?  I do recall an e-mail thread from years ago where as a group we decided the correct behavior for each situation.

**Comment by matchings** [comment]
I believe that currently if an ROI is deemed invalid, it is excluded from the matched set in the final output, regardless of whether it was matched or not. We discussed altering this behavior to give more weight / validity to cells with positive matches, but I don’t think anything actually happened on that front. 

Maybe we could add another category in addition to valid/invalid, and report in the cell_specimen_table whether the cell was matched/unmatched to an ROI in any other session and then let users decide whether to prioritize the valid/invalid call or the matched/unmatched call. But that might not work out as cleanly as we think if suite2P puts out a ton of small invalid masks, because the matching will likely match those small things to each other. 

I can do some quantification of how often a matched pair has one valid and one invalid so we can see how often it happens relative to matched but both valid or matched but both invalid.

**Comment by njmei** [comment]
I've run all the valid passed ophys experiments for container_id: 829561794 through our new suite2p pipeline and also through nway matching.

Nway matching results can be found at:
/allen/scratch/aibstemp/nicholasm/programs/braintv/production/visualbehavior/prod0/specimen_784057626/experiment_container_829561794/OphysNwayCellMatchingStrategy/container_run_1060561228

Notes:
- The query for linking visual_behavior_experiment_containers to ophys_experiments was a bit tricky. Saving here for posterity:
```
SELECT * FROM ophys_experiments oe
JOIN ophys_experiments_visual_behavior_experiment_containers oevbec ON oevbec.ophys_experiment_id=oe.id
JOIN visual_behavior_experiment_containers vbec ON vbec.id=oevbec.visual_behavior_experiment_container_id
WHERE vbec.id = 829561794 AND oe.workflow_state = 'passed'
```

- [ ] Waiting for code to reproduce the above plots and also general feedback on nway performance with new pipeline from @matchings

**Comment by njmei** [comment]
@matchings CC: @djkapner

Because the newest classifier has performed quite poorly, I ended up needing to backtrack a bit. Instead, I reprocessed the Suite2P segmented experiments with `container_id: 829561794` then used nway to match them to production ROIs as a 'proxy' for a good classifier to generate `valid` and `invalid` ROI labels. Then I ran the full nway-matching on the subsequent result.

Attached are **pairwise match count tables** for the **container run through Suite2P**:

![image](https://user-images.githubusercontent.com/43766899/98740921-ab239300-2360-11eb-8cbe-feef7942cd44.png)

As well as for **current production results**: 

![image](https://user-images.githubusercontent.com/43766899/98740980-bbd40900-2360-11eb-81a3-f79cda862eae.png)

Also included is the gist used to generate these tables:
https://gist.github.com/njmei/c53a10b06ea646c18b1e042b1aa283c6#file-nway_matching_with_suite2p-ipynb

**Comment by djkapner** [comment]
I am encouraged that the `valid_only` comparisons between production and Suite2P are similar numbers. I think the rest is as-expected: once you start mixing in invalid ROIs, Suite2P has many more, and the comparison to production matching doesn't hold up. I think re-visiting the impetus behind matching invalid cells would be worth discussing as a small group.

**Comment by djkapner** [comment]
I guess the question we want to know is, if we can define a function: `postprocess(nway_results, include_invalid=True)` to encapsulate Marina's description above, about what happens with invalid matched cells, then we can compare said function with production inputs vs. suite2p inputs.

**Comment by matchings** [comment]
Its good that the numbers are roughly in the same range, but it will be important to repeat this when we have the final classifier in place. 

I'm open to discussing the possibility of not matching invalid cells.

**Comment by njmei** [comment]
This ticket will be continued with:

https://github.com/AllenInstitute/ophys_nway_matching/issues/51
