### ISSUE TITLE
Review nway matching  production failures

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/ophys_nway_matching#52]
After the work from #45 was deployed, we have 11 failures in 
OPHYS_NWAY_CELL_MATCHING_REMAP_SPECIMENS_QUEUE
(232 out of 243 containers succeeded)
Review and catalog if it is a new problem or not.

**Comment by djkapner** [comment]
all but one of the registration pairs was "Identity". We agreed to fail jobs on this (no good registration found). Will check to see if there is an obvious data quality issue.
The other one:
http://lims2/job_logs?id=1063293228&utf8=%E2%9C%93 images are not same size? Need to see what is happening.

**Comment by djkapner** [comment]
experiment_container_782536745 experiments 775614751 792812544
dewarping issue?
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/5797e9cf-40c7-46b7-9476-db35e1f22777)

**Comment by djkapner** [comment]
@matchings @wbwakeman please offer comments on the above 9 failures. Editing that comment is fine, or, if new comment, please include the `experiment_container_X experiments Y Z` line so I know which one you're talking about,

3 main questions I would like to answer:
* 2 of these failures, I, as a human, can see that they are the same FOV, but challenging. If these are expected successes, I need to add a strategy to handle these as the 5 candidate strategies right now did not succeed.
* If we are going to continue to use nway matching as a general-purpose QC filter, I suggest 2 further modifications to it:
    * automatically output these projection comparisons in the event of a registration failure. add filepath to log for easy viewing.
    * output a registration failure/success matrix, in the log. This will make it easy to see which experiment is causing trouble.
* There are 2 other failures where one of the registration candidates failed because it expects same-sized images. Is it the case that 2 experiments would come out of motion correction with different frame sizes? If so, I need to add a little something to that one (PhaseCorrelate) so it can crop one of the images before attempting to align.

**Comment by matchings** [comment]
@djkapner there is only one case in the examples you provided that I can see that should have registered, i.e. i can see that its the same by eye. that is experiment_container_1018027896 experiments 905955240 915243101. Otherwise, they are all clearly mismatched and should have failed QC. 

for the first one, experiment_container_782536745 experiments 775614751 792812544, my guess is that it is not dewarping but an acquisition problem causing that stretched appearance. there are some parameters on the rig during recording that are set that can affect this type of thing (although i cant recall what the params are called right now). 

I agree that the projection comparisons, a registration success/failure matrix, and potentially the R/G and B/W overlay plots should be produced, but I would go further than just for problem cases and say that all containers that go through cell matching should have the set of diagnostic plots that we have been looking at. It would make life easier in a variety of ways. We can always produce these off pipeline to do QC, but i think as a general principle that each data processing step should produce as many metrics and visual artifacts as possible (barring large file sizes clogging up the server) to enable debugging and general QC and understanding of the data.

**Comment by wbwakeman** [comment]
For the two that failed because of differences in image sizes:

Container 814796558 is a real oddball in that it combines experiments from multiple rigs. I don't think that should be allowed.  It definitely seems like they tried to avoid it since I don't see mixed rigs for any of the other containers that I ran.

For 812858755, they all ran on 2P5, but the sessions overlap the date when new dewarping parameters were put in place (February 4 2019) .  There is a small chance that we can rescue this one - but we should remind the operations group that they should not make changes to a rig in the middle of collecting data for a single mouse.

**Comment by djkapner** [comment]
@matchings To summarize:

| container | note|
|-----------------|----------|
| 1018027896 | Marina thinks this one should register. Dan will try to develop a successful strategy to add |
| 814796558 | experiments from different rigs. motion corrected projections are different sizes |
| 812858755 | dewarping parameters changed for same mouse ? |
| 782536745 | rig problem, fail QC | 
| 1018027781 | fail QC |
| 1026722854 | fail QC |
| 1018027884 | fail QC |
| 1026722861 | fail QC |
| 1026722864 | fail QC |
| 1026722867 | fail QC |
| 1026722873 | fail QC |

I see action to take for me on the 1st one. The rest, how can we queue these up into your QC process?

**Comment by matchings** [comment]
First off, I dont think we should necessarily fail a full container if one experiment pair fails to register. For example, experiment_container_1018027884 experiments 905955230 914580662 - the rest of the container other than this pair appears to have worked fine. In a case like this, I would identify which of the two experiments was the problematic one and fail that specific experiment. 

Evaluating such cases and making judgement calls for how to deal with them is an ideal task for the QCathon, so having a list of containers & experiments with potential problems (like the examples provided above) would be very valuable. 

Second, i'm confused about some of the judgement calls here. I double checked container 1026722854 and it looks ok to me:

![container_1026722854](https://user-images.githubusercontent.com/21346970/99601391-28c84e00-29b4-11eb-8d3b-e28f0c542db3.png)

But again, deciding what to do with these is a good task for the QCathon.

**Comment by matchings** [comment]
At this point I think what would be most useful is to come up with a list of 1) all container / experiment_id combos that failed to run and complete, and 2) container / experiment_id combos that are suspicious according to some metric. 

candidate metrics include: 
* SSIM value of post-registration image pair is less than some threshold (perhaps 0.75) indicating non-optimal registration
* translation applied by registration is larger than some threshold, meaning a lot of registration was needed to align, presenting a potential case where registration was non-optimal because the images were so different to begin with 
* difference in SSIM value between pre-registration image pair and post-registration image pair is larger than some threshold, meaning a lot of registration was needed to align (this may be redundant with the previous one but i am curious how they relate to each other)
* fraction of cells matched across experiment pair is lower than some expected value (say 30%)
* relationship of these values to whether or not the experiment pair in question was the second paired plane in a mesoscope experiment (the deeper paired plane is not directly matched by the ophys operator, it just "comes along for the ride" after the upper paired plane is matched, which may be a source of registration challenges)
* any other metrics we can think of ?

If we have such a list, along with the metric values that prompted their inclusion, we can have members of the scientific team visually review them and determine whether 1) one or both of the experiments in the pair should fail, 2) the entire container should fail, 3) the can see the alignment by eye so the registration should have been able to find it, i.e. it could be rescued, or 4) everything looks fine. 

@djkapner are there any other things that you think would be useful to evaluate from a QC perspective? What information do you need from the QCathon to get to a state of completion with cell matching?

**Comment by djkapner** [comment]
I don't know why, but your plot for `1026722854` does not contain experiment `929655728` which is the one that is not aligning.

**Comment by djkapner** [comment]
re general QC and metrics:
> 2) container / experiment_id combos that are suspicious according to some metric

this is what this list is. the metric is "could not align any better than not aligning" It is based on relative measure of SSIM kind of like you described in one of your bullets above. I'll add the problem experiment to the table above.

the focus of this & the preceding issue (#45) was to fix registration, which I think we've made some good progress on. Out of 240+ containers, one pair of images you expected to align did not. I don't know the exact numbers, but that's probably like 0.999

your detailed comment above is about "nway/container QC" which is quite a bit broader topic. It also encompasses #36. That's fine, I'm familiar with all of it, but I'll probably write up a more detailed ticket so its visible (in particular to @wbwakeman) what needs to happen.

**Comment by matchings** [comment]
that is fair that my comment is more about nway/container QC which is a broader topic, and should probably be discussed elsewhere.

but i don't know that i agree that this list counts as "container / experiment_id combos that are suspicious according to some metric". i think this list goes under "all container / experiment_id combos that failed to run and complete". What i mean by "suspicious" is that the registration was able to run and provide results but the results may not be ideal (example is the double cells in the overlay). 

in any case, i agree that the work for this issue and #45 is complete as things currently stand. The registration runs for nearly all experiments and the registration output looks good to a first approximation. 

The second layer of more in depth QC is a separate task that falls primarily on the science team (with some help from you) to evaluate and then get back to you with any further issues.

**Comment by djkapner** [comment]
10 more failures from some runs last night:

@matchings let me know if any of these strike you as "should have aligned", as that's a separate effort from general QC, and I can write a pretty specific ticket for examples that should align. I think the rest will just be served up and digested during QC-a-thon with improved QC info.

experiment_container_1037672792 experiments 1039384487 1041379504
tough one
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/a3e6bb99-f042-4c58-8b1c-39bdde25a131)

-------------------

experiment_container_1037672801 experiments 1040982833 1041379508
data problem
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/6e8d0d2c-494d-48db-855d-1f3f0f196174)

---------------------

experiment_container_1046576772 experiments 1051460012 1052015568
don't see FOV match
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/a6321b34-831d-4c5c-82a8-87309f5c9755)

--------------------

experiment_container_1046576775 experiments 1051249022 1051460009
don't see FOV match. Several failures involving `1051460009`
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/986107b0-dfcc-475e-9aea-9ef2c70052c5)

-----------------------

experiment_container_1046576778 experiments 1051460011 1052015566
FOV match?
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/6036389b-f156-4642-bcf1-22eb22d4e386)

-----------------------

experiment_container_1052096551 experiments 1052212176 1058835259
several problems with `1058835259`
it is an FOV match, but looks funny
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/466646df-cef3-4b9a-94d6-9496f1561218)

-------------------------

experiment_container_1052096554 experiments 1057725798 1058835255
depth miss ?
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/48aa93ad-655b-44c5-a3e6-3b33fabc0f5e)

--------------------------

experiment_container_1052096557 experiments 1052212175 1058835258
?
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/f5a44616-fdd5-404c-b00a-e18886208640)

-----------------

experiment_container_1052096560 experiments 1052412564 1058835261
?
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/47de63d8-d610-4142-a2df-3b761a8f002a)

--------------------------

experiment_container_1052096563 experiments 1052412569 1058835265
could align...
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/97db5429-a038-4856-8b5a-f009a6583993)

**Comment by matchings** [comment]
I agree with all your diagnoses there. The first one is a tough call and the last one looks that way too. But I don’t know that it’s worth the effort to obsess over these two right now. We could find other problems with the full containers during the QCathon that would make these edge cases not a concern anyway. Let’s just wait until we have better QC states and then re-evaluate.

**Comment by djkapner** [comment]
In that case, from the previous batch, there is only one "should align" so, it sounds like qc is higher priority than improving that one registration. I will still write the ticket, but will help planning to elevate one over the other, especially if we find more that we think should have aligned.

**Comment by matchings** [comment]
Yeah I think it makes sense to prioritize QC so that we can get a more comprehensive list of cases that need attention before diving in to problem solving.

**Comment by djkapner** [comment]
closing this issue as we have now written its descendants: #36, #56, #57
