### ISSUE TITLE
Understand n-way cell matching algorithm

### ISSUE THREAD

**Issue by danielsf** [AllenInstitute/ophys_nway_matching#68]
Determine how the n-way cell matching algorithm is supposed to work, with an eye towards determining what might have gone wrong.

[Here is a poster](https://alleninstitute-my.sharepoint.com/:b:/g/personal/scott_daniel_alleninstitute_org/ETiclUrZnt1FmAhdtcNxnyEBe-7_eUgp0uxa05GXfog7QQ?e=NDk860) Marina once shared with me that purports to explain the algorithm.

I believe the LIMS queue you want is the `OPHYS_NWAY_CELL_MATCHING_QUEUE`. 

The code for the algorithm lives in

https://github.com/AllenInstitute/ophys_nway_matching

This issue should be time-boxed to no more than one week.

**Comment by morriscb** [comment]
One thing learned so far is that there are two queues for nway matching `OPHYS_NWAY_CELL_MATCHING_QUEUE` and `OPHYS_NWAY_CELL_MATCHING_REMAP_SPECIMENS_QUEUE` they run the same strategy with the slight difference being that latter sets an environment variable that deletes the current set of cell specimens from LIMS and remaps the new ROI associations to new cell_specimen_ids. Running `OPHYS_NWAY_CELL_MATCHING_QUEUE` with data that already has cell_specimen_ids assigned to the ROIs will result in a no-op. This is true even if the associations are different.

**Comment by morriscb** [comment]
Summarizing the main issue seen in #67: Running the OPHYS_NWAY_CELL_MATCHING_QUEUE on the same set of containers/ROIs more than once can end up with the data being left in a strange state. If re-run on the same data, the queue results in a no-op with respect to what ends up being stored in LIMS. Running the queue with data that has changed in the container on the same ROIs, results in the data being mismatched in LIMS in terms of which ROIs are matched together into cell_specimens. See the explanation on #67 for more detail.

This is the main understanding from this work as the algorithm appears to be running as expected given it's satisfactory performance on LearningmFish data that was recently run by myself (As was run on this [ticket](https://app.zenhub.com/workspaces/allensdk-10-5c17f74db59cfb36f158db8c/issues/alleninstitute/allensdk/2487)). If we'd like to understand the internals of the algorithm, I would suggest opening another ticket as what happened for this issue was more bookkeeping and understanding how the queue creates and updates cell_specimen_ids.

**Comment by morriscb** [comment]
I did encounter some issues that are related to input data quality rather than algorithmic failures. As mentioned on #67, the PNGs output by the legacy code are extremely washed out, having a dynamic range of 0 to ~20 in some cases rather than the allowed maximum of 255 for the uint8, PNG. Running some of the queue failures using custom images assuming this was the issue fixed only a few containers. Issues with Michael Buice's MultiscopeSignalNoise data seem to be deeper. And related to some sessions being mislabeled and associated with incorrect containers. Since these sessions are from spatially different locations, the nway matching fails at the pairwise step as they can't be registered to the rest of the experiments in the container. I've attached pdfs that show the containers that failed in the pairwise image registration either due to low image quality or bad container association below.

[https://app.zenhub.com/files/200717177/38d3ce64-790a-4d96-ab70-4ce5de7190db/download](https://app.zenhub.com/files/200717177/38d3ce64-790a-4d96-ab70-4ce5de7190db/download)

There are also a set of failures from a single specimen_id (1030507895) where none of the containers are even able create their slurm script for cluster submission. This apears to be due to the LIMS "state" variable for these containers/specimen being set to FAILED. I wasn't able to get more information from the Platform Team. After chatting with Marina, she suggested reaching out to Sam [last name unknown] and Pete Groblewski for the ophys team. Apparently, container association are put in by hand so the failures mentioned previously are likely due to bad data entry. This may also be true of the failed specimen, though I'll have to check. Closing this ticket and will open subisquent ones for resolving these issues and fully understanding the nway algorithm.
